# Generated by Django 3.1 on 2020-08-27 21:02

from django.db import migrations

def create_initial_years_of_birth(apps, schema_editor):
    YearsOfBirth = apps.get_model('app', 'YearOfBirth')
    birth2014 = YearsOfBirth(year=2014)
    birth2014.save()
    birth2015 = YearsOfBirth(year=2015)
    birth2015.save()

class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_initial_years_of_birth),
    ]
