# Generated by Django 3.1 on 2020-08-28 20:22

from django.db import migrations

import datetime

def create_initial_parties(apps, schema_editor):
    Party = apps.get_model('app', 'Party')
    party1 = Party(max_registrations=15, start_time=datetime.time(17,15), end_time=datetime.time(18), day='Monday')
    party1.save()
    party2 = Party(max_registrations=15, start_time=datetime.time(17,15), end_time=datetime.time(18), day='Tuesday')
    party2.save()
    party3 = Party(max_registrations=15, start_time=datetime.time(18), end_time=datetime.time(18,45), day='Tuesday')
    party3.save()

class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_party_day'),
    ]

    operations = [
        migrations.RunPython(create_initial_parties),
    ]
